version: "3"

services:
  api:
    build: .
    tty: true
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ./:/src
      - ../public:/public
    ports:
      - 8000:8000

  db:
    image: mysql:5.7.27
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
      MYSQL_DATABASE: isucari
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306